=== kir-r/DiamondFundTask/src/main/java/resource/diamondfundSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://diamondss.com/"
        xmlns:xs="https://diamondss.com/"
        elementFormDefault="qualified">

    <element name="gem">
        <complexType>
            <sequence>
                <element name="gemstone" type="xs:gemstone" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="gemstone">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[a-zA-Z]+"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="preciousness">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Precious"/>
                        <enumeration value="Semi-precious"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="origin">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[a-zA-Z]+\s?[a-zA-Z]*"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="VisualParameters" type="xs:VisualParameters"/>

            <element name="value">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[0-9]+"/>
                    </restriction>
                </simpleType>
            </element>

        </sequence>
    </complexType>

    <complexType name="VisualParameters">
        <sequence>
            <element name="color" type="string"/>
            <element name="transparency" type="integer">
                <simpleType>
                    <restriction base="integer">
                        <minInclusive value="0"/>
                        <maxInclusive value="100"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="cutting">
                <simpleType>
                    <restriction base="integer">
                        <pattern value="[0-9][0-9]"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

</schema>

=== kir-r/DiamondFundTask/src/main/java/resource/diamondfund.xml
<?xml version="1.0" encoding="UTF-8"?> <?xml-stylesheet type="text/xsl" href="diamondfund.xsl"?>
<gem xmlns="https://diamondss.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="https://diamondss.com/diamondfundSchema.xsd">
<gemstone>
    <name>Diamond</name>
    <preciousness>Precious</preciousness>
    <origin>South Africa</origin>
    <VisualParameters>
        <color>white</color>
        <transparency>100</transparency>
        <cutting>55</cutting>
    </VisualParameters>
    <value>112</value>
</gemstone>
<gemstone>
    <name>Sapphire</name>
    <preciousness>Precious</preciousness>
    <origin>South America</origin>
    <VisualParameters>
        <color>Green</color>
        <transparency>70</transparency>
        <cutting>54</cutting>
    </VisualParameters>
    <value>423</value>
</gemstone>
<gemstone>
    <name>Ruby</name>
    <preciousness>Precious</preciousness>
    <origin>Persia</origin>
    <VisualParameters>
        <color>red</color>
        <transparency>50</transparency>
        <cutting>44</cutting>
    </VisualParameters>
    <value>76</value>
</gemstone>
</gem>
